Revise: Write about direct startup for PW-A7400
brain-hackers/wiki.brainux.org pull request #43
Opened 2024-10-05 13:36 UTC by m-tsuru

## 概要

PW-A7400 の SD カードからの直接起動に関する記述を追加しました．

この記述は，[brain-hackers/buildbrain](https://github.com/brain-hackers/buildbrain) のリリース，[[2024-02-04-162841](https://github.com/brain-hackers/buildbrain/releases/tag/2024-02-04-162841)] に関連します．

2024-10-05 16:53 UTC, puhitaku requested changes
コメント箇所以外大丈夫です、修正したら勝手に merge してもらって OK です！

2024-10-05 16:53 UTC, puhitaku commented on collections/_beginners/get-started.md
> + 1. SD カードの先頭パーティションを開きます
ボリューム名が boot のパーティション、の括弧書きがここにも欲しいです

2024-10-06 02:59 UTC, m-tsuru commented
merge は push 権限の関係から puhitaku さんにしていただけたらと思います．

2024-10-06 02:59 UTC, puhitaku commented
あれ？ PR の merge はできるはずだけど
Approve しとくので試してみてほしいっす

2024-10-06 02:59 UTC, puhitaku approved these changes
LGTM

2024-10-06 03:21 UTC, m-tsuru commented
やっぱり Approval が一つ以上ないと merge できないみたいです．
approve 確認しました，merge します．

2024-10-06 03:21 UTC, merged